---

# Service Element Types for IPv4 Using in topology.
# by David Chan, 2014-06-12

serviceElementTypes:
    - name: ipv4Address
      description: The service element contains IPv4 address information.
      accessMethod:
          protocol: SNMP
          mib: IP-MIB
          index: [ ipAdEntAddr ]
      serviceElementTypeTranslates:
         - name: ipv4Address
           mapping: direct
           category: Network
      managementObjects:
          - name: ipAdEntAddr
            uri: ipAdEntAddr
            capability: ipv4Address
            unique: 1

          - name: ipAdEntIfIndex
            uri: ipAdEntIfIndex
            capability: ifIndex

          - name: ipAdEntNetMask
            uri: ipAdEntNetMask
            capability: ipNetMask

          - name: ipAdEntBcastAddr
            uri: ipAdEntBcastAddr
            capability: ipBraodcastAddress
            
          - name: ipAdEntReasmMaxSize
            uri: ipAdEntReasmMaxSize
            capability: ipReasmMaxSize

    - name: ipv4IpToPhysical
      description: The service element contains IPv4 address to physical mapping.
      accessMethod:
        protocol: SNMP
        mib: IP-MIB
        index: [ ipNetToMediaIfIndex ]
      serviceElementTypeTranslates:
        - name: ipv4IpToPhysical
          mapping: direct
          category: Network Element Specific Components

      managementObjects:
        - name: ipNetToMediaIfIndex
          uri: ipNetToMediaIfIndex

        - name: ipNetToMediaPhysAddress
          uri: ipNetToMediaPhysAddress
          capability: ipv4-netToMediaPhysAddress

        - name: ipNetToMediaNetAddress
          uri: ipNetToMediaNetAddress
          capability: ipv4-netToMediaNetAddress

        - name: ipNetToMediaType
          uri: ipNetToMediaType
          capability: ipv4-netToMediaType
...
