---

# technology definition for ipV4
# by David Chan, 2014-06-14

technologies:
    - name: ipv4
      provides: [ ipv4Address ]
      description: Discoverable ipv4 address.
      mechanisms:
          - name: IPv4Address
            description: Ip Address for IPv4
            capabilities:
                - name: ipv4Address
                  description: Ipv4 Address

                - name: ifIndex
                  description: ifIndex

                - name: ipNetMask
                  description: IP net mask

                - name: ipBraodcastAddress
                  description: IP Broadcast Address

                - name: ipReasmMaxSize
                  description: IP Reasm Max Size.

          - name: IPtoPhyscial
            description: Ip Address to physical address mapping
            capabilities:
                - name: ipv4-netToMediaPhysAddress
                  description: Ipv4 net to media physical address

                - name: ipv4-netToMediaNetAddress
                  description: IP net media net address

                - name: ipv4-netToMediaType
                  description: IP media type
...
