---

# management definition for CDP

serviceElementTypes:
    - name: cisco-cdp-global
      description: Cisco enterprise CDP MIB, global variables.
      vendor: cisco
      accessMethod: 
          protocol: SNMP
          mib: CISCO-CDP-MIB
          index: null
      serviceElementTypeTranslates:
         - name: cdpGlobal
           mapping: direct
           category: System
      managementObjects:
          - name: cdpGlobalRun
            uri: cdpGlobalRun
            capability: cdp-global-run

          - name: cdpGlobalDeviceId
            uri: cdpGlobalDeviceId
            capability: cdp-global-deviceId

          - name: cdpGlobalMessageInterval
            uri: cdpGlobalMessageInterval
            capability: cdp-global-cdpGlobalMessageInterval

          - name: cdpGlobalHoldTime
            uri: cdpGlobalHoldTime
            capability: cdp-global-cdpGlobalHoldTime
            
    - name: vlanInterface
      description: CISCO interface which contains CISCO own attributes and associations with VLAN SE.
      vendor: cisco
      extendServiceElementType: interface
      accessMethod: 
          protocol: SNMP
      serviceElementTypeTranslates:
          - name: vlanInterface
            mapping: direct
            category: Interface
      associations:
         - name: ifVlanAssociation
           associateServiceElementTypeName: ciscoVtpVlan
           managementObjects:
              - name: vmVlanType
                uri: vmVlanType
                capability: vmVlanType
                       
              - name: vmVlan
                uri: vmVlan
                capability: vmVlan
                       
              - name: vmPortStatus
                uri: vmPortStatus
                capability: vmPortStatus
                       
    - name: cisco-cdp-interface
      description: Cisco enterprise CDP MIB, per-interface attributes.
      vendor: cisco
      extendServiceElementType: vlanInterface
      accessMethod: 
          protocol: SNMP
          mib: CISCO-CDP-MIB
          index: [ cdpInterfaceIfIndex ]
      serviceElementTypeTranslates:
          - name: cdpInterface
            mapping: direct
            category: Interface
      managementObjects:
          - name: cdpInterfaceEnable
            uri: cdpInterfaceEnable
            capability: cdp-interface-enable

          - name: cdpInterfaceName
            uri: cdpInterfaceName
            capability: cdp-interface-name

    - name: cisco-system
      description: Cisco system
      vendor: cisco
      extendServiceElementType: systemCommon
      accessMethod:
          protocol: SNMP
      serviceElementTypeTranslates:
         - name: ciscoSystem
           mapping: direct
           category: System
           iconName: grayRouter.jpg
      managementObjects:
      
    - name: cisco-ipv4Addr
      description: Cisco IP v4 Address
      vendor: cisco
      extendServiceElementType: ipv4Address
      accessMethod:
          protocol: SNMP
      serviceElementTypeTranslates:
         - name: ciscoIpv4Addr
           mapping: direct
           category: Network
      managementObjects:
         - name: ipAdEntReasmMaxSize
           uri: ipAdEntReasmMaxSize
           capability: ipReasmMaxSize

    - name: cisco-cdp-cache
      description: Cisco enterprise CDP MIB, device cache per interface.
      vendor: cisco
      accessMethod: 
          protocol: SNMP
          mib: CISCO-CDP-MIB
          index: [ cdpCacheIfIndex, cdpCacheDeviceIndex ]
      serviceElementTypeTranslates:
         - name: cdpCache
           mapping: direct
           category: Network Element Specific Components
      managementObjects:
         - name: cdpCacheAddressType
           uri: cdpCacheAddressType
           capability: cdp-cache-addressType

         - name: cdpCacheAddress
           uri: cdpCacheAddress
           capability: cdp-cache-address

         - name: cdpCacheVersion
           uri: cdpCacheVersion
           capability: cdp-cache-version

         - name: cdpCacheDeviceId
           uri: cdpCacheDeviceId
           capability: cdp-cache-deviceId

         - name: cdpCacheDevicePort
           uri: cdpCacheDevicePort
           capability: cdp-cache-devicePort

         - name: cdpCachePlatform
           uri: cdpCachePlatform
           capability: cdp-cache-platform

...
