---

# management definition for CDP
# by Loren Jan Wilson, 2014-05-21

serviceElementTypes:
    - name: cisco-cdp-global
      description: Cisco enterprise CDP MIB, global variables.
      vendor: cisco
      accessMethod: 
          protocol: SNMP
          mib: CISCO-CDP-MIB
          index: null
      serviceElementTypeTranslates:
         - name: cpdGlobal
           mapping: direct
           category: system
      managementObjects:
          - name: cdpGlobalRun
            uri: cdpGlobalRun
            capability: cdp-global-run

          - name: cdpGlobalDeviceId
            uri: cdpGlobalDeviceId
            capability: cdp-global-deviceId

    - name: cisco-cdp-interface
      description: Cisco enterprise CDP MIB, per-interface attributes.
      vendor: cisco
      accessMethod: 
          protocol: SNMP
          mib: CISCO-CDP-MIB
          index: [ cdpInterfaceIfIndex ]
      serviceElementTypeTranslates:
         - name: cpdInterface
           mapping: direct
           category: portIf
      managementObjects:
          - name: cdpInterfaceIfIndex
            uri: cdpInterfaceIfIndex
            capability: cdp-interface-index

          - name: cdpInterfaceEnable
            uri: cdpInterfaceEnable
            capability: cdp-interface-enable

          - name: cdpInterfaceName
            uri: cdpInterfaceName
            capability: cdp-interface-name

    - name: cisco-cdp-cache
      description: Cisco enterprise CDP MIB, device cache per interface.
      vendor: cisco
      accessMethod: 
          protocol: SNMP
          mib: CISCO-CDP-MIB
          index: [ cdpCacheIfIndex, cdpCacheDeviceIndex ]
      serviceElementTypeTranslates:
         - name: cdpCache
           mapping: direct
           category: cache
      managementObjects:
          - name: cdpCacheIfIndex
            uri: cdpCacheIfIndex
            capability: cdp-cache-ifIndex

          - name: cdpCacheDeviceIndex
            uri: cdpCacheDeviceIndex
            capability: cdp-cache-deviceIndex

          - name: cdpCacheAddressType
            uri: cdpCacheAddressType
            capability: cdp-cache-addressType

          - name: cdpCacheAddress
            uri: cdpCacheAddress
            capability: cdp-cache-address

          - name: cdpCacheVersion
            uri: cdpCacheVersion
            capability: cdp-cache-version

          - name: cdpCacheDeviceId
            uri: cdpCacheDeviceId
            capability: cdp-cache-deviceId

          - name: cdpCacheDevicePort
            uri: cdpCacheDevicePort
            capability: cdp-cache-devicePort

          - name: cdpCachePlatform
            uri: cdpCachePlatform
            capability: cdp-cache-platform

...
