---

# technology definition for CDP
# by Loren Jan Wilson, 2014-05-21

technologies:
    # CDP, the Cisco Discovery Protocol.
    # 3 mechanism types: cdp-global, cdp-interface, cdp-cache (cache entry).
    - name: cdp
    #  provides: [ neighbor-discovery ]
      parent: neighbor discovery
      description: Cisco Discovery Protocol
      mechanisms:
          - name: cdp-global
            description: CDP global information on this device.
            capabilities:
                - name: cdp-global-run
                  description: Whether CDP is running on this device.

                - name: cdp-global-deviceId
                  description: The global device ID being advertised via CDP.

                - name: cdp-global-cdpGlobalHoldTime
                  description: The time for the receiving device holds CDP message.

                - name: cdp-global-cdpGlobalLastChange
                  description: Indicates the time when the cache table was last changed.

                - name: cdp-global-cdpGlobalDeviceIdFormatCpb
                  description: Indicate the Device-Id format capability of the device.

                - name: cdp-global-cdpGlobalDeviceIdFormat
                  description: An indication of the format of Device-Id contained in the corresponding instance of cdpGlobalDeviceId.

                - name: cdp-global-cdpGlobalMessageInterval
                  description: The interval at which CDP messages are to be generated.
        
          - name: cdp-interface
            index: [ cdp-interface-index ]
            description: >
                Each interface on the box that is capable of doing CDP has a
                corresponding CDP interface service element (certain types of
                physical interfaces only).
            capabilities:
                - name: cdp-interface-name
                  description: The name of each interface as advertised by CDP.

                - name: cdp-interface-enable
                  description: Whether CDP is enabled on each interface.

                - name: cdp-interface-cdpInterfaceExtendedTrust
                  description: Indicates the value to be sent by Extended Trust TLV.

                - name: cdp-interface-cdpInterfaceMessageInterval
                  description: The interval at which CDP messages are to be generated on this interface.

                - name: cdp-interface-cdpInterfaceCosForUntrustedPort
                  description: Indicates the value to be sent by COS for Untrusted Ports TLV.

          - name: cdp-cache
            index: [ cdp-cache-ifIndex, cdp-cache-deviceIndex ]
            description: >
                For every remote CDP neighbor on each interface, there is a
                device entry in the local CDP cache.
            capabilities:
                - name: cdp-cache-addressType
                  description: > 
                      The type of address advertised by the remote device.
                      (e.g. IP, IPv6, CLNS)

                - name: cdp-cache-address
                  description: The address advertised by the remote device.

                - name: cdp-cache-version
                  description: The OS version string advertised by the remote device.

                - name: cdp-cache-deviceId
                  description: The device ID of the remote device.

                - name: cdp-cache-port
                  description: The port on the remote device that we're connected to.

                - name: cdp-cache-platform
                  description: The remote device's hardware platform.

...
