#This is the default Harvard-specific Business Service list. It is possible to change this, but it may have
#unexpected side effects. The initial letter of each name element is in capitols. The exception
#is for hyphenated words. This is the element that the user interface presents for selections.

name: Business Service-tree
description: business service-tree
parent: root
businessServices:
      - name: User Services
        description:  user services
        parent: business service-tree
        userServices:
          - name: Email
            description:  email
            parent: user services
            
          - name: Human Resource Management Systems
            description:  human resource management systems
            parent: user services
            
          - name: Payroll
            description: payroll 
            parent: user services
            
          - name: Student Information System
            description:  student information system
            parent: user services
                      
          - name: Library Resources
            description:  library resources
            parent: user services

      - name: IT Provider Services
        description:  provider services
        parent: business service-tree
        providerServices:
          - name: IAM
            description:  Identity and Access Management
            parent: provider services
