#This is the default Harvard-specific environment list. It is possible to change this, but it may have
#unexpected side effects. The initial letter of each name element is in capitols. The exception
#is for hyphenated words. This is the element that the user interface presents for selections.


- name: Production
  description:  production

- name: Stage
  description:  stage
        
- name: Test
  description:  test
        
- name: Development
        
