#This is the default Integer Category-tree. It is possible to change this, but it may have
#unexpected side effects. The initial letter of each name element is in capitols. The exception
#is for hyphenated words. This is the element that the user interface presents for selections.

name: Category-tree
description: category-tree
parent: root
categories:
      - name: System
        description: system
        parent: category-tree
        categories:
        - name: Virtual
          description: virtual
          parent: system
          categories:
            - name: Interface
              description: interface
              parent: virtual
              
        - name: Physical
          description: physical
          parent: system
          categories:
            - name: Passive
              description:  passive
              parent: physical
              categories:
                - name: Rack
                  description:  rack
                  parent: passive
            
                - name: Switch Panel
                  description:  switch panel
                  parent: passive
                  
                - name: Fiber
                  description: fiber
                  parent: passive
                  
            - name: Network Element Categories
              description:  Network Element Categories
              parents: [physical, virtual]
              categories:
                - name: Router
                  description:  router
                  parent: network element categories
                  
                - name: Switch
                  description:  switch
                  parent: network element categories
                  
                - name: Switch/Router
                  description:  switch/router
                  parent: network element categories
                  
                - name: Firewall
                  description:  firewall
                  parent: network element categories

                - name: Vlan
                  description: vlan
                  parent: network element categories
                  
                - name: NAT
                  description:  nat
                  parent: network element categories
                  
                - name: Load Balancer
                  description:  load balancer
                  parent: network element categories
            
                - name: Network Element Specific Components
                  description: network element specific components
                  parent: network element categories
                  categories:       
                    - name: Container
                      description: slot is one type of container
                      parent: network element specific components

                    - name: Module
                      description: linecard, fpc, etc.
                      parent: network element specific components
            
                    - name: Routing Engine
                      description: routing engine
                      parent: network element specific components
                      
                    - name: Supervisor Board
                      description: supervisor board
                      parent: network element specific components  
            
                    - name: Feature Card
                      description: crypto, ssl, extra processing, etc.
                      parent: network element spefic components
                  
            - name: Server Categories
              description:  server categories
              parents: [physical, virtual]
              categories:
                - name: General Purpose
                  description:  general purpose
                  parent: server categories
                  
                - name: Web
                  description:  web
                  parent: server categories
                  
                - name: Database
                  description:  web
                  parent: server categories
                  
                - name: LDAP
                  description:  LDAP
                  parent: server categories               
                  
                - name: File
                  description:  file
                  parent: server categories
       
                - name: Storage
                  description:  storage
                  parent: server categories
                  
                - name: Application
                  description:  application
                  parent: server categories
              
                - name: Server Specific Components
                  description: server specific components
                  parent: server categories
                  categories:       
                  - name: Raid Array
                    description: raid array
                    parent: hardware
          
                  - name: Raid Controller
                    description: raid controller
                    parent: hardware
                     
            - name: Common System Components
              description:  common system components
              parents: [network element categories, server categories]
              categories:
                - name: Chassis
                  description: chassis
                  parent: common system components
        
                - name: Backplane
                  description: backplane
                  parent: common system components
               
                - name: Midplane
                  description: midplane
                  parent: common system components

                - name: Memory
                  description: memory
                  parent: common system components
        
                - name: Stack
                  description: stack
                  parent: common system components

                - name: Port
                  description: port
                  parent: common system components
        
                - name: Optic
                  description: optic
                  parent: common system components
        
                - name: Fan
                  description: fan
                  parent: common system components
        
                - name: Power Supply
                  description: power supply
                  parent: common system components
        
                - name: Sensor
                  description: sensor
                  parent: common system components
        
                - name: CPU
                  description: cpu
                  parent: common system components
        
                - name: PCMCIA Card
                  description: pcmcia card
                  parent: common system components
        
                - name: Disk
                  description: disk
                  parent: common system components
 
      - name: Software
        description: software
        parent: category-tree
        categories:
        - name: Overall Operating System
          description: overall operating system
          parent: software

        - name: Per-card Operating System
          description: per-card operating system
          parent: software
        
        - name: Middleware/Application Server
          description: middleware/application server
          parent: software
          
        - name: Database
          description: database
          parent: software
          
        - name: File Service
          description: file service
          parent: software
          
        - name: Network
          description: network
          parent: software
          
        - name: Other Undefined
          description: other undefined
          parent: software
            
      - name: Inter Device Links
        description: inter device links
        parent: category-tree
        
      - name: unknown
        description: unknown category
        parent: category-tree
