#This is the default Integer Category-tree. It is possible to change this, but it may have
#unexpected side effects.
name: category-tree
description: category-tree
parent: root
categories:
      - name: System
        description: system
        parent: category-tree
        categories:
        - name: Virtual
          description: virtual
          parent: system
          categories:
            - name: interface
              description: interface
              parent: virtual
              
        - name: Physical
          description: physical
          parent: system
          categories:
            - name: Passive
              description:  passive
              parent: physical
              categories:
                - name: Rack
                  description:  rack
                  parent: passive
            
                - name: Switch Panel
                  description:  switch panel
                  parent: passive
                  
                - name: Fiber
                  description: fiber
                  parent: passive
                  
            - name: Network Element Categories
              description:  Network Element Categories
              parents: [physical, virtual]
              categories:
                - name: Router
                  description:  router
                  parent: network element categories
                  
                - name: Switch
                  description:  switch
                  parent: network element categories
                  
                - name: Switch/Router
                  description:  switch/router
                  parent: network element categories
                  
                - name: Firewall
                  description:  firewall
                  parent: network element categories
                  
                - name: NAT
                  description:  nat
                  parent: network element categories
                  
                - name: Load Balancer
                  description:  load balancer
                  parent: network element categories
            
                - name: Network Element Specific Components
                  description: network element specific components
                  parent: network element categories
                  categories:       
                    - name: container
                      description: slot is one type of container
                      parent: network element specific components

                    - name: module
                      description: linecard, fpc, etc.
                      parent: network element specific components
            
                    - name: routing engine
                      description: routing engine
                      parent: network element specific components
                      
                    - name: Supervisor Board
                      description: supervisor board
                      parent: network element specific components  
            
                    - name: feature card
                      description: crypto, ssl, extra processing, etc.
                      parent: network element spefic components
                  
            - name: Server Categories
              description:  server categories
              parents: [physical, virtual]
              categories:
                - name: General Purpose
                  description:  general purpose
                  parent: server categories
                  
                - name: Web
                  description:  web
                  parent: server categories
                  
                - name: Database
                  description:  web
                  parent: server categories
                  
                - name: LDAP
                  description:  LDAP
                  parent: server categories               
                  
                - name: File
                  description:  file
                  parent: server categories
       
                - name: Storage
                  description:  storage
                  parent: server categories
                  
                - name: Application
                  description:  application
                  parent: server categories
              
                - name: Server Specific Components
                  description: server specific components
                  parent: server categories
                  categories:       
                  - name: raid array
                    description: raid array
                    parent: hardware
          
                  - name: raid controller
                    description: raid controller
                    parent: hardware
                     
            - name: Common System Components
              description:  common system components
              parents: [network element categories, server categories]
              categories:
                - name: chassis
                  description: chassis
                  parent: common system components
        
                - name: backplane
                  description: backplane
                  parent: common system components
               
                - name: mibplane
                  description: mibplane
                  parent: common system components

                - name: Memory
                  description: memory
                  parent: common system components
        
                - name: stack
                  description: stack
                  parent: common system components

                - name: port
                  description: port
                  parent: common system components
        
                - name: optic
                  description: optic
                  parent: common system components
        
                - name: fan
                  description: fan
                  parent: common system components
        
                - name: power supply
                  description: power supply
                  parent: common system components
        
                - name: sensor
                  description: sensor
                  parent: common system components
        
                - name: cpu
                  description: cpu
                  parent: common system components
        
                - name: pcmcia card
                  description: pcmcia card
                  parent: common system components
        
                - name: disk
                  description: disk
                  parent: common system components
 
      - name: software
        description: software
        parent: category-tree
        categories:
        - name: overall operating system
          description: overall operating system
          parent: software

        - name: per-card operating system
          description: per-card operating system
          parent: software
        
        - name: Middleware/Application Server
          description: middleware/application server
          parent: software
          
        - name: Database
          description: database
          parent: software
          
        - name: File Service
          description: file service
          parent: software
          
        - name: Network
          description: network
          parent: software
          
        - name: Other Undefined
          description: other undefined
          parent: software
            
      - name: Inter Device Links
        description: inter device links
        parent: category-tree
        
