---

# Interfaces technology definition for Integer
# by Loren Jan Wilson, 2014-05-07

technologies:
    # These are physical and virtual interfaces, found in the IF-MIB in the
    # case of SNMP.
    - name: interfaces
      description: Physical and virtual interfaces
      mechanismTypes:
          # A mechanism for a couple of global attributes related to
          # interfaces.
          - name: interface-global
            description: Global attributes for the interfaces on this system.
            capabilities:
                - name: interface-global-number
                  description: The total number of interfaces on this system.

                - name: interface-global-lastChangeTime
                  description: > 
                      The system uptime at the last time an interface was added
                      or deleted.

          # An interface has many capabilities. Some of these will have null
          # values depending on whether or not the interfaces extension table
          # is supported by the device. 
          - name: interface
            description: >
                Each interface is represented as a single component called an
                interface. No surprises here.
            capabilities:
                - name: interface-index
                  description: > 
                      Also known as the ifIndex, interfaces are tied to other
                      technologies using this number.

                - name: interface-name
                  description: >
                      The name for the interface that can be used on the
                      console to configure this interface.

                - name: interface-longname
                  description: >
                      Another name for the interface, originally supported by
                      ifDescr. Sometimes this is the same as interface-name,
                      sometimes not.

                - name: interface-description
                  description: >
                      This is the text in the "description" field on the
                      interface, set by the local administrator.

                - name: interface-type
                  description: >
                      The IANA type of the interface. (e.g. ethernetCsmacd,
                      propVirtual, softwareLoopback)

                - name: interface-physicalAddress
                  description: >
                      The physical address for this interface, usually a MAC
                      address.

                - name: interface-adminStatus
                  type: admin
                  description: Administrative status (up or down).

                - name: interface-operationalStatus
                  type: health
                  description: Operational status (up or down).

                - name: interface-speed
                  description: The speed of this interface, in megabits.

                - name: interface-mtu
                  description: The current MTU of this interface.

                - name: interface-lastChangeTime
                  description: The system uptime the last time this interface was changed.

                - name: interface-inputOctets
                  type: counter
                  description: > 
                      Input octets counter. 
                      64 bit if we can get it, 32 bit otherwise.

                - name: interface-outputOctets
                  type: counter
                  description: > 
                      Output octets counter. 
                      64 bit if we can get it, 32 bit otherwise.

                - name: interface-inputUnicastPackets
                  type: counter
                  description: > 
                      Input unicast packets counter. 
                      64 bit if we can get it, 32 bit otherwise.

                - name: interface-outputUnicastPackets
                  type: counter
                  description: > 
                      Output unicast packets counter. 
                      64 bit if we can get it, 32 bit otherwise.

                - name: interface-inputMulticastPackets
                  type: counter
                  description: > 
                      Input multicast packets counter. This will be empty if
                      the interface extension table isn't supported.

                - name: interface-outputMulticastPackets
                  type: counter
                  description: > 
                      Output multicast packets counter. This will be empty if
                      the interface extension table isn't supported.

                - name: interface-inputBroadcastPackets
                  type: counter
                  description: > 
                      Input broadcast packets counter. This will be empty if
                      the interface extension table isn't supported.

                - name: interface-outputBroadcastPackets
                  type: counter
                  description: > 
                      Output broadcast packets counter. This will be empty if
                      the interface extension table isn't supported.

                - name: interface-inputDiscards
                  type: counter
                  description: >
                      The number of inbound packets which were discarded even
                      though no errors had been detected. This usually means
                      input buffers filled up on the interface.

                - name: interface-outputDiscards
                  type: counter
                  description: >
                      The number of outbound packets which were discarded even
                      though no errors had been detected. This usually means
                      output buffers filled up on the interface.

                - name: interface-inputErrors
                  type: counter
                  description: Input errors counter. 

                - name: interface-outputErrors
                  type: counter
                  description: Output errors counter. 

                - name: interface-inputUnknownProtocols
                  type: counter
                  description: >
                      The number of packets or transmission units received via
                      this interface which were discarded because of an unknown
                      or unsupported protocol.  

                - name: interface-linkUpDownTrapEnable
                  description: > 
                      Whether or not SNMP traps are sent on link up/down
                      events.

                - name: interface-promiscuousMode
                  description: > 
                      Whether or not this interface is in promiscuous mode.

                - name: interface-connectorPresent
                  description: > 
                      Whether or not this interface has a physical connector
                      present. This is a good way to find out whether an
                      interface is physical or virtual without checking for
                      physical entity relations.

...
