#This is the default Integer Technology-tree. It is possible to change this, but it may have
#unexpected side effects.
name: technology-tree
description: technology-tree
parent: root
technologies:
      - name: Networking
        description:  networking
        parent: technology-tree
#Physcial connectivity items are interfaces
        technologies:
        - name: Physical Connectivity
          description: physical connectivity
          parent: networking
          technologies:
            - name: Ethernet Physical Layer
              description: ethernet physical layer
              parent: physical connectivity
              technologies:
                - name: 1000base-T
                  description: 1000base-T
                  parent: ethernet physical layer
    
                - name: 10GBASE-SR
                  description: 10GBASE-SR
                  parent: ethernet physical layer
  
            - name: 802.11 wireless LAN
              description: Wi-Fi
              parent: physical connectivity
    
            - name: 802.16 wireless MAN
              description: WiMAX
              parent: physical connectivity

            - name: Link Layer Protocols
              descritpion:  link layer protocols
              parent: networking
              technologies:
                - name: Data Link Protocols
                  description: data link protocols
                  parent: link layer protocols
                  technologies:
                  - name: Ethernet
                    description: Ethernet
                    parent: data link protocols
          
                  - name: PPP
                    description: PPP
                    parent: data link protocols
          
                  - name: PPTP
                    description: PPTP
                    parent: data link protocols

#Discovery Protocols are not interfaces.

                - name: Neighbor Discovery
                  description: neighbor discovery
                  parent: link layer protocols
                  technologies:
                  - name: CDP
                    description: Cisco Discovery Protocol
                    parent: neighbor discovery
          
                  - name: LLDP
                    description: Link-layer Discovery Protocol
                    parent: neighbor discovery
          
                  - name: LLDP-MED
                    description: Link-layer Discovery Protocol Media Endpoint Discovery
                    parent: neighbor discovery
          
                  - name: NDP
                    description: IPv6 Neighbor Discovery Protocol
                    parent: neighbor discovery
          
                  - name: FDP
                    description: Foundry Discovery Protocol
                    parent: neighbor discovery
          
                  - name: EDP
                    description: Extreme Discovery Protocol
                    parent: neighbor discovery
          
                  - name: LLTD
                    description: Microsoft Link-layer Topology Discovery protocol
                    parent: neighbor discovery

                - name: Link Bonding
                  description: link bonding
                  parent: link layer protocols
                  technologies:
                    - name: Host-to-host bonded link schemes
                      description: host-to-host bonded link schemes
                      parent: link bonding
                      technologies:
                      - name: Cisco EtherChannel
                        description: Cisco EtherChannel
                        parent: host-to-host bonded link schemes
          
                      - name: Juniper Aggregated Ethernet
                        description: juniper aggregated ethernet
                        parent: host-to-host bonded link schemes
          
                      - name: Avaya Multi-Link Trunking
                        description: avaya multi-link trunking
                        parent: host-to-host bonded link schemes
          
                      - name: Linux Bonding driver
                        description: Linux Bonding driver
                        parent: host-to-host bonded link schemes
          
                      - name: Linux Team driver
                        description: Linux Team driver
                        parent: host-to-host bonded link schemes
          
                      - name: Microsoft load balancing and failover
                        description: microsoft load balancing and failover
                        parent: host-to-host bonded link schemes
          
                    - name: link bonding types
                      description: link bonding types
                      parent: link layer protocols
                      technologies:
                        - name: static single-sided configuration
                          description: host-only
                          parent: link bonding types
                          technologies:
                          - name: active-backup
                            description: active-backup
                            parent: static single-sided configuration
          
                          - name: broadcast
                            description: broadcast
                            parent: static single-sided configuration
          
                          - name: adaptive transmit
                            description: adaptive transmit
                            parent: static single-sided configuration
          
                          - name: adaptive transmit and receive
                            description: adaptive transmit and receive
                            parent: static single-sided configuration
          
                        - name: static dual-sided configuration
                          description: static dual-sided configuration
                          parent: link bonding types
                          technologies:
                          - name: round-robin
                            description: round-robin
                            parent: static dual-sided configuration
          
                          - name: xor
                            description: xor
                            parent: static dual-sided configuration
          
                        - name: dynamic protocols
                          description: dynamic protocols
                          parent: link bonding types
                          technologies:
                          - name: lacp
                            description: lacp
                            parent: dynamic protocols
          
                          - name: pagp
                            description: pagp
                            parent: dynamic protocols
          
                    - name: Proprietary Multi-chassis Bonding Schemes
                      description: switch-side proprietary, host-side LACP
                      parent: link bonding
                      technologies:
                      - name: Juniper Multi-Chassis Link Aggregation
                        description: Alcatel-Lucent
                        parent: proprietary multi-chassis bonding schemes
          
                      - name: Brocade Multi-Chassis Trunking
                        description: Brocade Multi-Chassis Trunking
                        parent: proprietary multi-chassis bonding schemes
          
                      - name: Arista Multi-Chassis Link Aggregation
                        description: Arista Multi-Chassis Link Aggregation
                        parent: proprietary multi-chassis bonding schemes
          
                      - name: Cisco Virtual Port Channel
                        description: vPC
                        parent: proprietary multi-chassis bonding schemes
          
                      - name: Force10 Virtual Link Trunking
                        description: Force10 Virtual Link Trunking
                        parent: proprietary multi-chassis bonding schemes

#Virtual Networking and Spanning Trees. All of these can be interfaces.
  
        - name: VLANs
          description: Virtual Local Area Networks
          parent: networking
          technologies:
            - name: VLAN tagging protocols
              description: VLAN tagging protocols
              parent: VLANs
              technologies:
              - name: 802.1q vlan trunking
                description: 802.1q vlan trunking
                parent: VLAN tagging protocols
  
              - name: Cisco ISL
                description: or IEEE 802.10
                parent: VLAN tagging protocols
  
              - name: LANE
                description: LAN emulation
                parent: VLAN tagging protocols
  
            - name: VLAN Registration Protocols
              description: VLAN registration protocols
              parent: VLANs
              technologies:
              - name: Cisco VTP
                description: VLAN Trunking Protocol
                parent: VLAN registration protocols
  
              - name: MVRP
                description: Multiple VLAN Registration Protocol, part of MRP (IEEE 802.1ak)
                parent: VLAN registration protocols
  
            - name: VLAN trunk negotiation protocols
              description: VLAN trunk negotiation protocols
              parent: VLANs
              technologies:
              - name: Cisco DTP
                description: Dynamic Trunking Protocol
                parent: VLAN trunk negotiation protocols
  
            - name: Spanning-tree protocol versions and alternatives
              description: Spanning-tree protocol versions and alternatives
              parent: VLANs
              technologies:
              - name: standards-based spanning-tree versions - IEEE STP
                description: 802.1d) - RSTP (802.1w, 802.1d-2004) - MSTP (Multiple Spanning Tree Protocol) (802.1s, 802.1q-2005
                parent: Spanning-tree protocol versions and alternatives
                technologies:
                - name: vendor-proprietary spanning-tree implementations
                  description: vendor-proprietary spanning-tree implementations
                  parent: Spanning-tree protocol versions and alternatives
                  technologies:
                  - name: Cisco PVST
                    description: Cisco PVST
                    parent: vendor-proprietary spanning-tree implementations
  
                  - name: Cisco PVST+
                    description: Cisco PVST+
                    parent: vendor-proprietary spanning-tree implementations
  
                  - name: Cisco RPVST
                    description: Cisco RPVST
                    parent: vendor-proprietary spanning-tree implementations
  
                  - name: Cisco MISTP
                    description: Cisco MISTP
                    parent: vendor-proprietary spanning-tree implementations
  
                  - name: Extreme EAPS
                    description: Extreme EAPS
                    parent: vendor-proprietary spanning-tree implementations
  
            - name: Spanning-tree replacement protocols
              description: Spanning-tree replacement protocols
              parent: VLANs
              technologies:
              - name: SPB
                description: Shortest Path Bridging
                parent: Spanning-tree replacement protocols
  
              - name: TRILL
                description: Transparent Interconnection of Lots of Links
                parent: Spanning-tree replacement protocols

#Encryption - Not treated as interfaces.
        - name: Traffic Encryption Protocols
          description: traffic encryption protocols
          parent: networking
          technologies:
            - name: IPSEC
              description: IPSEC
              parent: traffic encryption protocols
              technologies:
              - name: AH
                description: AH
                parent: IPSEC
  
              - name: ESP
                description: ESP
                parent: IPSEC
  
              - name: SA
                description: SA
                parent: IPSEC

#Other Layer 2.5 Technologies All of these can be interfaces.

      - name: packet-switched networking
        description: packet-switched networking
        parent: networking
        technologies:
        - name: Frame Relay
          description: Frame Relay
          parent: packet-switched networking

        - name: ATM
          description: ATM
          parent: packet-switched networking

        - name: MPLS
          description: MPLS
          parent: packet-switched networking

      - name: tunneling
        description: tunneling
        parent: technology-tree
        technologies:
        - name: Cisco GRE
          description: Generic Routing Encapsulation, virtual point-to-point links
          parent: tunneling

        - name: mGRE
          description: multipoint GRE
          parent: tunneling

        - name: IP-VPN
          description: based on PPP and IPSEC
          parent: tunneling
          technologies:
          - name: MPLS VPN tunnels
            description: MPLS VPN tunnels
            parent: tunneling
            technologies:
            - name: PW/point-to-point
              description: pseudowire
              parent: MPLS VPN tunnels

            - name: VPLS
              description: Virtual Private LAN Service
              parent: MPLS VPN tunnels

            - name: VPRN
              description: Virtual Private Routed Network
              parent: MPLS VPN tunnels

#Layer 2 Switching
   
      - name: Switching
        description: switching
        parent: networking
        technologies:
          - name: Ethernet Switching
            description: ethernet switching
            parent: switching
            technologies:
            - name: CAM table
              description: CAM table
              parent: ethernet switching

#Network Layer. Not Treated as Interfaces.
 
      - name: Network Layer Protocols
        description: network layer protocols
        parent: networking
        technologies:
        - name: IPv4
          description: IPv4
          parent: network layer protocols

        - name: IPv6
          description: IPv6
          parent: network layer protocols

        - name: CLNS
          description: CLNS
          parent: network layer protocols

      - name: IP routing protocols
        description: IP routing protocols
        parent: networking
        technologies:
          - name: Interior Gateway Protocols
            description: interior gateway protocols
            parent: IP routing protocols
            technologies:
              - name: Link-State
                description: link-state
                parent: interior gateway protocols
                technologies:
                - name: OSPFv2
                  description: IPv4
                  parent: link-state

                - name: OSPFv3
                  description: IPv6
                  parent: link-state

                - name: IS-IS
                  description: IS-IS
                  parent: link-state

              - name: Distance Vector
                description: distance vector
                parent: interior gateway protocols
                technologies:
                - name: RIP
                  description: RIP
                  parent: distance vector

                - name: RIPv2
                  description: RIPv2
                  parent: distance vector

                - name: IGRP
                  description: IGRP
                  parent: distance vector

                - name: EIGRP
                  description: EIGRP
                  parent: distance vector

          - name: Exterior Gateway Protocols
            description: exterior gateway protocols
            parent: IP routing protocols
            technologies:
            - name: BGP - iBGP - EBGP
              description: BGP - iBGP - EBGP
              parent: exterior gateway protocols

#Not treated as interfaces.

      - name: IP Multicast Protocols
        description: protocols for delivery of multicast services
        parent: networking
        technologies:
        - name: IGMP
          description: IGMP
          parent: IP multicast protocols

        - name: PIM
          description: protocol independent multicast
          parent: IP multicast protocols

        - name: DVMRP
          description: distance vector multicast routing protocol
          parent: IP multicast protocols

        - name: MOSPF
          description: MOSPF
          parent: IP multicast protocols

        - name: MBGP
          description: MBGP
          parent: IP multicast protocols

        - name: GMRP
          description: GMRP
          parent: IP multicast protocols

        - name: MLD
          description: MLD
          parent: IP multicast protocols

