---

# management definition for physical hardware
# by David Chan, 2014-06-12

serviceElementTypes:
    - name: entity-physical
      description: The physical table in the ENTITY-MIB.
      accessMethod:
          protocol: SNMP
          mib: ENTITY-MIB
          index: [ entPhysicalIndex ]
      vendor: cisco
      serviceElementTypeTranslates:
         - name: cevChassis 
           mapping: subObjIdentify
           category: Chassis
         - name: cevBackplane
           mapping: subObjIdentify
           category: Backplane
         - name: cevContainer
           mapping: subObjIdentify
           category: Container
         - name: cevPowerSupply
           mapping: subObjIdentify
           category: Power Supply
         - name: cevFan
           mapping: subObjIdentify
           category: Fan
         - name: cevSensor
           mapping: subObjIdentify
           category: Sensor
         - name: cevModule
           mapping: subObjIdentify
           category: Module
         - name: cevPort
           mapping: subObjIdentify
           category: Port
         - name: cevStack
           mapping: subObjIdentify
           category: Stack
         - name: cevMidplane
           mapping: subObjIdentify
           category: Midplane
              
      managementObjects:
          - name: entPhysicalDescr
            uri: entPhysicalDescr
            capability: physical-description

          - name: entPhysicalVendorType
            uri: entPhysicalVendorType
            capability: physical-vendorType

          - name: entPhysicalClass
            uri: entPhysicalClass
            capability: physical-name

          - name: entPhysicalParentRelPos
            uri: entPhysicalParentRelPos
            capability: physical-relativePosition

          - name: entPhysicalName
            uri: entPhysicalName
            capability: physical-name
            
          - name: entPhysicalHardwareRev
            uri: entPhysicalHardwareRev
            capability: physical-hardwareRevision
            categories: [module chassis]

          - name: entPhysicalFirmwareRev
            uri: entPhysicalFirmwareRev
            capability: physical-firmwareRevision
            categories: [module chassis]
            specificAttribute: firmware

          - name: entPhysicalSoftwareRev
            uri: entPhysicalSoftwareRev
            capability: physical-softwareRevision
            categories: [module chassis]

          - name: entPhysicalSerialNum
            uri: entPhysicalSerialNum
            capability: physical-serialNumber
            categories: [module chassis]
            unique: 1

          - name: entPhysicalMfgName
            uri: entPhysicalMfgName
            capability: physical-vendor

          - name: entPhysicalModelName
            uri: entPhysicalModelName
            capability: physical-model
            specificAttribute: model

          - name: entPhysicalIsFRU
            uri: entPhysicalIsFRU
            capability: physical-fru

